apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hive.fullname" . }}-metastore
  labels:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/component: metastore
    {{- include "hive.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hive.name" . }}
      app.kubernetes.io/component: metastore
      {{- include "hive.labels" . | nindent 6 }}
  serviceName: {{ include "hive.fullname" . }}-metastore
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hive.name" . }}
        app.kubernetes.io/component: metastore
        {{- include "hive.labels" . | nindent 8 }}
    spec:
      containers:
      - name: metastore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 10; done"
        #- "/opt/hive/bin/hive --service metastore"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 16010
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 16010
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf
      volumes:
      - name: hive-config
        configMap:
          name: {{ include "hive.fullname" . }}
