# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-metastore
  labels:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/component: metastore
    {{- include "hive.labels" . | nindent 4 }}
spec:
  ports:
  - name: thrift
    port: 9083
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: {{ .Release.Name }}
