# Default values for jupyter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gradiant/jupyter
  tag: 6.0.3
  pullPolicy: IfNotPresent

lab: true

service:
  type: ClusterIP
  externalPort: 8888
  nodePort:
    http:

persistence:
  enabled: true
  storageClass:
  accessMode: ReadWriteOnce
  size: 50Gi

## Ingress configuration
## Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - jupyter.127-0-0-1.nip
  tls: []
    # - secretName: jupyter-tls
    #   hosts:
    #     - jupyter.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
