# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-httpfs
  labels:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: httpfs
    {{- include "hdfs.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: httpfs
    port: {{ .Values.httpfs.port }}
    targetPort: {{ .Values.httpfs.port }}
    nodePort: 32468
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: httpfs
    app.kubernetes.io/instance: {{ .Release.Name }}
