dependencies:
- name: hive-metastore
  alias: metastore
  version: ~0.1.3
  repository: https://gradiant.github.io/charts
  condition: metastore.enabled
- name: hdfs
  version: ~0.1.10
  repository: https://gradiant.github.io/charts
  condition: hdfs.enabled
