name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm 2
        uses: azure/setup-helm@v1
        with:
          version: 'v2.16.3'

      - name: Install Helm repositories
        run: |
          helm init --client-only
          helm repo add gradiant https://gradiant.github.io/charts/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
